
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ProduitWS", targetNamespace = "http://webservice.soap_provider.soap.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProduitWS {


    /**
     * 
     * @param produit
     * @return
     *     returns proxy.Produit
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduit", targetNamespace = "http://webservice.soap_provider.soap.org/", className = "proxy.GetProduit")
    @ResponseWrapper(localName = "getProduitResponse", targetNamespace = "http://webservice.soap_provider.soap.org/", className = "proxy.GetProduitResponse")
    @Action(input = "http://webservice.soap_provider.soap.org/ProduitWS/getProduitRequest", output = "http://webservice.soap_provider.soap.org/ProduitWS/getProduitResponse")
    public Produit getProduit(
        @WebParam(name = "Produit", targetNamespace = "")
        Integer produit);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Produit>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listeProduits", targetNamespace = "http://webservice.soap_provider.soap.org/", className = "proxy.ListeProduits")
    @ResponseWrapper(localName = "listeProduitsResponse", targetNamespace = "http://webservice.soap_provider.soap.org/", className = "proxy.ListeProduitsResponse")
    @Action(input = "http://webservice.soap_provider.soap.org/ProduitWS/listeProduitsRequest", output = "http://webservice.soap_provider.soap.org/ProduitWS/listeProduitsResponse")
    public List<Produit> listeProduits();

}
