
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ProduitWebServiceService", targetNamespace = "http://webservice.soap_provider.soap.org/", wsdlLocation = "http://127.0.0.1:8090/?wsdl")
public class ProduitWebServiceService
    extends Service
{

    private static final URL PRODUITWEBSERVICESERVICE_WSDL_LOCATION;
    private static final WebServiceException PRODUITWEBSERVICESERVICE_EXCEPTION;
    private static final QName PRODUITWEBSERVICESERVICE_QNAME = new QName("http://webservice.soap_provider.soap.org/", "ProduitWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8090/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUITWEBSERVICESERVICE_WSDL_LOCATION = url;
        PRODUITWEBSERVICESERVICE_EXCEPTION = e;
    }

    public ProduitWebServiceService() {
        super(__getWsdlLocation(), PRODUITWEBSERVICESERVICE_QNAME);
    }

    public ProduitWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUITWEBSERVICESERVICE_QNAME, features);
    }

    public ProduitWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, PRODUITWEBSERVICESERVICE_QNAME);
    }

    public ProduitWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUITWEBSERVICESERVICE_QNAME, features);
    }

    public ProduitWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProduitWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProduitWS
     */
    @WebEndpoint(name = "ProduitWSPort")
    public ProduitWS getProduitWSPort() {
        return super.getPort(new QName("http://webservice.soap_provider.soap.org/", "ProduitWSPort"), ProduitWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProduitWS
     */
    @WebEndpoint(name = "ProduitWSPort")
    public ProduitWS getProduitWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.soap_provider.soap.org/", "ProduitWSPort"), ProduitWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUITWEBSERVICESERVICE_EXCEPTION!= null) {
            throw PRODUITWEBSERVICESERVICE_EXCEPTION;
        }
        return PRODUITWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
